In [24]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.preprocessing import StandardScaler

In [25]:
dataset = pd.read_csv('heart_attack.csv')

In [2]:
dataset.head(10)

NameError: name 'dataset' is not defined

In [4]:
dataset.head(10)

NameError: name 'dataset' is not defined

In [28]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])


In [29]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])


In [30]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

[[6.400e+01 1.000e+00 6.600e+01 ... 1.600e+02 1.800e+00 1.200e-02]
 [2.100e+01 1.000e+00 9.400e+01 ... 2.960e+02 6.750e+00 1.060e+00]
 [5.500e+01 1.000e+00 6.400e+01 ... 2.700e+02 1.990e+00 3.000e-03]
 ...
 [4.500e+01 1.000e+00 8.500e+01 ... 9.600e+01 1.240e+00 4.250e+00]
 [5.400e+01 1.000e+00 5.800e+01 ... 4.430e+02 5.800e+00 3.590e-01]
 [5.100e+01 1.000e+00 9.400e+01 ... 1.340e+02 5.089e+01 1.770e+00]]
['negative' 'positive' 'negative' ... 'positive' 'positive' 'positive']


In [31]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
print(x)

[[6.400e+01 1.000e+00 6.600e+01 ... 1.600e+02 1.800e+00 1.200e-02]
 [2.100e+01 1.000e+00 9.400e+01 ... 2.960e+02 6.750e+00 1.060e+00]
 [5.500e+01 1.000e+00 6.400e+01 ... 2.700e+02 1.990e+00 3.000e-03]
 ...
 [4.500e+01 1.000e+00 8.500e+01 ... 9.600e+01 1.240e+00 4.250e+00]
 [5.400e+01 1.000e+00 5.800e+01 ... 4.430e+02 5.800e+00 3.590e-01]
 [5.100e+01 1.000e+00 9.400e+01 ... 1.340e+02 5.089e+01 1.770e+00]]


In [32]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = ct.fit_transform(x)
print(x)

  (0, 46)	1.0
  (0, 75)	1.0
  (0, 76)	66.0
  (0, 77)	160.0
  (0, 78)	83.0
  (0, 79)	160.0
  (0, 80)	1.8
  (0, 81)	0.012
  (1, 3)	1.0
  (1, 75)	1.0
  (1, 76)	94.0
  (1, 77)	98.0
  (1, 78)	46.0
  (1, 79)	296.0
  (1, 80)	6.75
  (1, 81)	1.06
  (2, 37)	1.0
  (2, 75)	1.0
  (2, 76)	64.0
  (2, 77)	160.0
  (2, 78)	77.0
  (2, 79)	270.0
  (2, 80)	1.99
  (2, 81)	0.003
  (3, 46)	1.0
  :	:
  (1315, 81)	0.172
  (1316, 27)	1.0
  (1316, 75)	1.0
  (1316, 76)	85.0
  (1316, 77)	168.0
  (1316, 78)	104.0
  (1316, 79)	96.0
  (1316, 80)	1.24
  (1316, 81)	4.25
  (1317, 36)	1.0
  (1317, 75)	1.0
  (1317, 76)	58.0
  (1317, 77)	117.0
  (1317, 78)	68.0
  (1317, 79)	443.0
  (1317, 80)	5.8
  (1317, 81)	0.359
  (1318, 33)	1.0
  (1318, 75)	1.0
  (1318, 76)	94.0
  (1318, 77)	157.0
  (1318, 78)	79.0
  (1318, 79)	134.0
  (1318, 80)	50.89
  (1318, 81)	1.77


In [33]:
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 ... 1 1 1]


In [34]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [35]:
print(x_train)

  (0, 37)	1.0
  (0, 76)	59.0
  (0, 77)	110.0
  (0, 78)	65.0
  (0, 79)	208.0
  (0, 80)	2.53
  (0, 81)	0.024
  (1, 15)	1.0
  (1, 75)	1.0
  (1, 76)	62.0
  (1, 77)	76.0
  (1, 78)	55.0
  (1, 79)	106.0
  (1, 80)	0.71
  (1, 81)	0.007
  (2, 47)	1.0
  (2, 75)	1.0
  (2, 76)	70.0
  (2, 77)	142.0
  (2, 78)	75.0
  (2, 79)	108.0
  (2, 80)	165.0
  (2, 81)	0.058
  (3, 34)	1.0
  (3, 75)	1.0
  :	:
  (1051, 80)	1.9
  (1051, 81)	0.006
  (1052, 12)	1.0
  (1052, 75)	1.0
  (1052, 76)	60.0
  (1052, 77)	202.0
  (1052, 78)	88.0
  (1052, 79)	197.0
  (1052, 80)	12.89
  (1052, 81)	0.003
  (1053, 42)	1.0
  (1053, 75)	1.0
  (1053, 76)	53.0
  (1053, 77)	102.0
  (1053, 78)	61.0
  (1053, 79)	303.0
  (1053, 80)	14.07
  (1053, 81)	0.816
  (1054, 64)	1.0
  (1054, 76)	90.0
  (1054, 77)	125.0
  (1054, 78)	73.0
  (1054, 79)	89.0
  (1054, 80)	2.04
  (1054, 81)	0.147


In [36]:
print(x_test)

  (0, 45)	1.0
  (0, 75)	1.0
  (0, 76)	89.0
  (0, 77)	87.0
  (0, 78)	53.0
  (0, 79)	81.0
  (0, 80)	0.961
  (0, 81)	0.015
  (1, 40)	1.0
  (1, 76)	80.0
  (1, 77)	167.0
  (1, 78)	97.0
  (1, 79)	92.0
  (1, 80)	1.67
  (1, 81)	0.017
  (2, 39)	1.0
  (2, 75)	1.0
  (2, 76)	51.0
  (2, 77)	130.0
  (2, 78)	70.0
  (2, 79)	92.0
  (2, 80)	4.25
  (2, 81)	0.008
  (3, 64)	1.0
  (3, 76)	88.0
  :	:
  (260, 79)	97.0
  (260, 80)	1.69
  (260, 81)	0.005
  (261, 50)	1.0
  (261, 76)	60.0
  (261, 77)	124.0
  (261, 78)	58.0
  (261, 79)	180.0
  (261, 80)	1.08
  (261, 81)	0.003
  (262, 53)	1.0
  (262, 75)	1.0
  (262, 76)	82.0
  (262, 77)	80.0
  (262, 78)	42.0
  (262, 79)	102.0
  (262, 80)	1.18
  (262, 81)	0.01
  (263, 37)	1.0
  (263, 76)	50.0
  (263, 77)	110.0
  (263, 78)	90.0
  (263, 79)	219.0
  (263, 80)	6.78
  (263, 81)	2.53


In [37]:
print(y_train)

[1 0 1 ... 1 1 1]


In [38]:
print(y_test)

[1 1 0 0 0 0 0 0 1 1 0 1 1 0 1 0 1 0 0 1 0 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 1
 0 1 1 0 1 0 0 0 1 0 1 1 0 1 1 1 0 0 1 1 0 0 1 1 0 1 1 1 0 0 0 1 1 1 1 1 0
 1 1 0 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 1 0 1 0
 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 0 0 1 1 0 0 0 1 1 0 0 0 0
 1 1 0 1 1 0 1 1 0 1 1 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 1 1 0 1 1
 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 0 1 0 1 1 1 1 0 1 1 1 0 0 0 0 1 1 0 1 1 1 1
 1 0 1 1 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 0 0 1 0 0 1 0 0 1 1 0 1
 1 0 0 0 1]


In [40]:
from sklearn.preprocessing import StandardScaler

In [50]:
sc = StandardScaler(with_mean=False)
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [51]:
print(x_train)

  (0, 37)	4.751770196292861
  (0, 76)	1.0313876864609586
  (0, 77)	4.226959730949028
  (0, 78)	4.66667129912809
  (0, 79)	2.6640703027449444
  (0, 80)	0.0554067243565128
  (0, 81)	0.020090349303835953
  (1, 15)	14.560383302123675
  (1, 75)	2.103597975233199
  (1, 76)	1.0838311281454143
  (1, 77)	2.9204449050193286
  (1, 78)	3.948721868492999
  (1, 79)	1.3576512119757889
  (1, 80)	0.015548922645503593
  (1, 81)	0.005859685213618818
  (2, 47)	4.751770196292861
  (2, 75)	2.103597975233199
  (2, 76)	1.2236803059706292
  (2, 77)	5.456620743588745
  (2, 78)	5.3846207297631805
  (2, 79)	1.3832672725791058
  (2, 80)	3.6134820232508353
  (2, 81)	0.04855167748427021
  (3, 34)	6.706833209782944
  (3, 75)	2.103597975233199
  :	:
  (1051, 80)	0.041609792995009616
  (1051, 81)	0.005022587325958988
  (1052, 12)	12.317506448287277
  (1052, 75)	2.103597975233199
  (1052, 76)	1.0488688336891105
  (1052, 77)	7.762235142288217
  (1052, 78)	6.317954989588799
  (1052, 79)	2.523181969426702
  (1052, 80)	0.28

In [52]:
print(x_test)

  (0, 45)	4.751770196292861
  (0, 75)	2.103597975233199
  (0, 76)	1.555822103305514
  (0, 77)	3.343140878114232
  (0, 78)	3.805131982365981
  (0, 79)	1.0374504544343293
  (0, 80)	0.021045795299054863
  (0, 81)	0.012556468314897469
  (1, 40)	6.574516852564925
  (1, 76)	1.398491778252147
  (1, 77)	6.417293409713526
  (1, 78)	6.96410947716038
  (1, 79)	1.1783387877525715
  (1, 80)	0.036572818053508455
  (1, 81)	0.014230664090217133
  (2, 39)	8.73902691746921
  (2, 75)	2.103597975233199
  (2, 76)	0.8915385086357438
  (2, 77)	4.995497863848852
  (2, 78)	5.025646014445635
  (2, 79)	1.1783387877525715
  (2, 80)	0.09307453696252152
  (2, 81)	0.00669678310127865
  (3, 64)	18.779497287672353
  (3, 76)	1.538340956077362
  :	:
  (260, 79)	1.2423789392608635
  (260, 80)	0.03701081587450856
  (260, 81)	0.004185489438299157
  (261, 50)	6.221401393893226
  (261, 76)	1.0488688336891105
  (261, 77)	4.764936423978905
  (261, 78)	4.164106697683526
  (261, 79)	2.3054454542985097
  (261, 80)	0.0236518823340